[[redirects]]
  from = "/recaptcha"
  to = "/games/recaptcha"
  status = 301

[[redirects]]
  from = "/delivery"
  to = "/games/autobahn-delivery"
  status = 301

[[redirects]]
  from = "/asteroids"
  to = "/games/asteroids"
  status = 301

[[redirects]]
  from = "/pong"
  to = "/games/pong"
  status = 301

[build]
  command = "git submodule update --remote && (cd public/games/recaptcha && npm ci && npm run build && cp -r dist/. .) && npm ci && npm run build"
  publish = "dist"

[build.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"